name: symphony
description: A music player via streaming like Spotify and Deezer.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_analytics: ^9.1.6
  firebase_auth: ^3.3.15
  firebase_database: ^9.0.12
  flutterfire: ^0.0.1
  google_sign_in: ^5.3.0
  get: ^4.6.1
  google_fonts: ^2.3.2
  flutter_feather_icons: ^2.0.0+1
  palette_generator: ^0.3.3
  cloud_firestore: ^3.1.14
  just_audio: ^0.9.24
  just_audio_background: ^0.0.1-beta.5
  audio_video_progress_bar: ^0.10.0
  modal_bottom_sheet: ^2.0.1
  home_widget: ^0.1.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#4D3FC6"
  adaptive_icon_foreground: "assets/icons/adaptive_icon.png"

flutter:
  uses-material-design: true

  assets:
    - ./assets/login.png
    - ./assets/login2.png
    - ./assets/google.png
    - ./assets/profile.jpg
